### ISSUE TITLE
不能获取到已安装的chrome的包信息

### ISSUE THREAD

**Issue by nonameShijian** [JonaNorman/WebViewUpgrade#10]
设备: 安卓14小米澎湃

在这个配置的情况下
![b5aca9d79014fce86bb391816135a20](https://github.com/JonaNorman/WebViewUpgrade/assets/88574031/d58a72f8-8155-463b-a262-2de5bc2e10ea)
app单独使用android.permission.REQUEST_INSTALL_PACKAGES
权限不能获取到已安装的chrome的包信息,必须使用queries明确指定chrome才行
但是系统给app这个权限默认是允许的(仅运行时允许)
![890fb6cac5845e929f54e7485d5c7ce](https://github.com/JonaNorman/WebViewUpgrade/assets/88574031/5c4c6056-42eb-4d20-820c-99856b8c1947)
![bfbc608855d982be31818f0d890f65d](https://github.com/JonaNorman/WebViewUpgrade/assets/88574031/e57dfc92-91f3-4bd7-8d69-fc564f144543)

**Comment by JonaNorman** [comment]
14系统权限变更
