### ISSUE TITLE
Is this the only active and open source way

### ISSUE THREAD

**Issue by tkkcc** [JonaNorman/WebViewUpgrade#12]
Is there any other ways to embed modern web runtime in android, like wechat app. I think it's a common request but only found this nice solution. Can't believe it's a project started in 2024.

**Comment by JonaNorman** [comment]
其他方案，据我所知就只有x5内核或者自己编译chromium内核了，但是这些方案需要有人一直去维护才能保证chromium内核一直最新，所以我想到可以直接在应用内升级webview内核apk，这样就能让内核的功能是最新的
