### ISSUE TITLE
upgrade failed

### ISSUE THREAD

**Issue by yansy1** [JonaNorman/WebViewUpgrade#16]
message:WebView only can replace before SystemWebView init
stackTrace:com.norman.webviewup.lib.WebViewReplaceException: WebView only can replace beforeSystem WebView init
at
com.norman.webviewup.lib.WebViewReplace.checkWebView(WebViewReplace.java:168)
at
com.norman.webviewup.lib.WebViewReplace.replace(WebViewReplace.java:64)
at com.norman.webviewup.lib.WebViewUpgrade
$1$1.run(WebViewUpgrade.java:94)at
com.norman.webviewup.lib.util.HandlerUtils.runin
MainThread(HandlerUtils.iava:1 1)
设备是android6.0

**Comment by JonaNorman** [comment]
在初始化webview之前，调用

**Comment by yansy1** [comment]
还没有进行webview使用，只是升级，但是还是报错

**Comment by JonaNorman** [comment]
> 更新提示成功了，用的是华为的包 com.huawei.webview，但是adb shell am start -a android.intent.action.VIEW -d [https://liulanmi.com/labs/core.html这样去看的时候版本还是没变](https://liulanmi.com/labs/core.html%E8%BF%99%E6%A0%B7%E5%8E%BB%E7%9C%8B%E7%9A%84%E6%97%B6%E5%80%99%E7%89%88%E6%9C%AC%E8%BF%98%E6%98%AF%E6%B2%A1%E5%8F%98)

只会影响APP内部的WebView
