### ISSUE TITLE
要加载的版本小于系统版本会导致降级

### ISSUE THREAD

**Issue by nonameShijian** [JonaNorman/WebViewUpgrade#3]
有别人帮我测试了一下，他内核是121，然后我app是内置的119版本，这样的情况也会变成119版本。

这个情况应该不覆盖的，会导致降级的存在

(
一般来说apk版本就是Agent版本
但是某个遥遥领先的webview版本号并不按这个来，所以判断apk内的userAgent或许会麻烦一些？
)

**Comment by JonaNorman** [comment]
现在除了华为可以用apk的版本判断
<img width="1126" alt="image" src="https://github.com/JonaNorman/WebViewUpgrade/assets/4536178/daf79d7a-9b7e-4fcb-9e1b-22a01140f660">
而解决华为WebView获取实际的chrome的版本只能从useragent入手，而useragent现在只能在new WebView去获取，而new WebView后就不能去动态去切换WebView，这就无解了，可能需要从其他角度入手
