### ISSUE TITLE
是否可以做个api来避免下载和内置两个步骤，直接采用手机安装的chrome.apk作为Webview实现

### ISSUE THREAD

**Issue by nonameShijian** [JonaNorman/WebViewUpgrade#5]

**Comment by JonaNorman** [comment]
已更新，新增了source的概念，可以解决asset、网络下载、chrome安装在手机的三种情况
<img width="1215" alt="image" src="https://github.com/JonaNorman/WebViewUpgrade/assets/4536178/bbaef8ca-a0f8-4568-a84e-1b0881b69712">
