### ISSUE TITLE
升级成功后，重启 App，WebView 还是升级前的版本

### ISSUE THREAD

**Issue by 2015-D33** [JonaNorman/WebViewUpgrade#9]
设备 VIVO X90，Android14

**Comment by nonameShijian** [comment]
那你是 在升级回调完成后创建的webview吗？包括new webview或其子类，以及setContent一个布局xml中的webview标签，都是要在完成的那个回调后才能调用的。如果你是按操作完成的话那才可能是bug

**Comment by 2015-D33** [comment]
我的操作步骤是用 demo 点了 upgrade 成功后点 test，显示的是更新后的版本。退出 demo 杀掉进程再打开 demo 直接点 test，显示的版本是未升级前的版本

**Comment by JonaNorman** [comment]
> 我的操作步骤是用 demo 点了 upgrade 成功后点 test，显示的是更新后的版本。退出 demo 杀掉进程再打开 demo 直接点 test，显示的版本是未升级前的版本

“退出 demo 杀掉进程再打开 demo 直接点 test”需要在点击test之前点击upgrade，每次重启后点test之前都要点upgrade

**Comment by 2015-D33** [comment]
感谢，看了原理的文章，是初始化做了 hook，我以为是升级了系统的 webview apk。
